//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdleMaster.localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IdleMaster.localization.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;About.
        /// </summary>
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Accept.
        /// </summary>
        internal static string accept {
            get {
                return ResourceManager.GetString("accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Add.
        /// </summary>
        internal static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Game to Blacklist.
        /// </summary>
        internal static string add_game_blacklist {
            get {
                return ResourceManager.GetString("add_game_blacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display advanced authentication information.
        /// </summary>
        internal static string advanced_auth {
            get {
                return ResourceManager.GetString("advanced_auth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle Master Authentication Data.
        /// </summary>
        internal static string auth_data {
            get {
                return ResourceManager.GetString("auth_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badge page didn&apos;t load, will retry in __num__ seconds.
        /// </summary>
        internal static string badge_didnt_load {
            get {
                return ResourceManager.GetString("badge_didnt_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Blacklist.
        /// </summary>
        internal static string blacklist {
            get {
                return ResourceManager.GetString("blacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Blacklist Current Game.
        /// </summary>
        internal static string blacklist_current_game {
            get {
                return ResourceManager.GetString("blacklist_current_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to card drops remaining.
        /// </summary>
        internal static string card_drops_remaining {
            get {
                return ResourceManager.GetString("card_drops_remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display information above
        ///
        ///[WARNING]
        ///Do not share this information with anyone,
        ///as it could potentially be used by an attacker to log into
        ///your Steam account..
        /// </summary>
        internal static string cookie_warning {
            get {
                return ResourceManager.GetString("cookie_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently in-game.
        /// </summary>
        internal static string currently_ingame {
            get {
                return ResourceManager.GetString("currently_ingame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit.
        /// </summary>
        internal static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        internal static string file {
            get {
                return ResourceManager.GetString("file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Game.
        /// </summary>
        internal static string game {
            get {
                return ResourceManager.GetString("game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to games left to idle.
        /// </summary>
        internal static string games_left_to_idle {
            get {
                return ResourceManager.GetString("games_left_to_idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string general {
            get {
                return ResourceManager.GetString("general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        internal static string hours {
            get {
                return ResourceManager.GetString("hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hrs on record.
        /// </summary>
        internal static string hrs_on_record {
            get {
                return ResourceManager.GetString("hrs_on_record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle each game individually.
        /// </summary>
        internal static string idle_individual {
            get {
                return ResourceManager.GetString("idle_individual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle Master is connected to Steam.
        /// </summary>
        internal static string idle_master_connected {
            get {
                return ResourceManager.GetString("idle_master_connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle Master is not connected to Steam.
        /// </summary>
        internal static string idle_master_notconnected {
            get {
                return ResourceManager.GetString("idle_master_notconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle Master Settings.
        /// </summary>
        internal static string idle_master_settings {
            get {
                return ResourceManager.GetString("idle_master_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idle now.
        /// </summary>
        internal static string idle_now {
            get {
                return ResourceManager.GetString("idle_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle games with more than 2 hours individually, then simultaneously.
        /// </summary>
        internal static string idle_onethenmany {
            get {
                return ResourceManager.GetString("idle_onethenmany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle games simultaneously up to 2 hours, then individually.
        /// </summary>
        internal static string idle_simultaneous {
            get {
                return ResourceManager.GetString("idle_simultaneous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idling Behavior.
        /// </summary>
        internal static string idling_behavior {
            get {
                return ResourceManager.GetString("idling_behavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idling complete, no more card drops available.
        /// </summary>
        internal static string idling_complete {
            get {
                return ResourceManager.GetString("idling_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idling Order.
        /// </summary>
        internal static string idling_order {
            get {
                return ResourceManager.GetString("idling_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idling paused.
        /// </summary>
        internal static string idling_paused {
            get {
                return ResourceManager.GetString("idling_paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Steam client status.
        /// </summary>
        internal static string ignore_client_status {
            get {
                return ResourceManager.GetString("ignore_client_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface Language.
        /// </summary>
        internal static string interface_language {
            get {
                return ResourceManager.GetString("interface_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading next game....
        /// </summary>
        internal static string loading_next {
            get {
                return ResourceManager.GetString("loading_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Idle Master Blacklist.
        /// </summary>
        internal static string manage_blacklist {
            get {
                return ResourceManager.GetString("manage_blacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize Idle Master to system tray.
        /// </summary>
        internal static string minimize_to_tray {
            get {
                return ResourceManager.GetString("minimize_to_tray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next check.
        /// </summary>
        internal static string next_check {
            get {
                return ResourceManager.GetString("next_check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not in game.
        /// </summary>
        internal static string not_ingame {
            get {
                return ResourceManager.GetString("not_ingame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Official Group.
        /// </summary>
        internal static string official_group {
            get {
                return ResourceManager.GetString("official_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;OK.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default (Alphabetical Order).
        /// </summary>
        internal static string order_default {
            get {
                return ResourceManager.GetString("order_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prioritize games with the lowest number of available drops.
        /// </summary>
        internal static string order_least {
            get {
                return ResourceManager.GetString("order_least", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prioritize games with the highest number of available drops.
        /// </summary>
        internal static string order_most {
            get {
                return ResourceManager.GetString("order_most", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prioritize games with the highest card values.
        /// </summary>
        internal static string order_value {
            get {
                return ResourceManager.GetString("order_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Pause Idling.
        /// </summary>
        internal static string pause_idling {
            get {
                return ResourceManager.GetString("pause_idling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Login to Steam.
        /// </summary>
        internal static string please_login {
            get {
                return ResourceManager.GetString("please_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please restart the application for language changes to take effect..
        /// </summary>
        internal static string please_restart {
            get {
                return ResourceManager.GetString("please_restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please wait....
        /// </summary>
        internal static string please_wait {
            get {
                return ResourceManager.GetString("please_wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading badge page.
        /// </summary>
        internal static string reading_badge_page {
            get {
                return ResourceManager.GetString("reading_badge_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Release Notes.
        /// </summary>
        internal static string release_notes {
            get {
                return ResourceManager.GetString("release_notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle Master Release Notes.
        /// </summary>
        internal static string release_notes_title {
            get {
                return ResourceManager.GetString("release_notes_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Resume Idling.
        /// </summary>
        internal static string resume_idling {
            get {
                return ResourceManager.GetString("resume_idling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle Master is saving your information.
        /// </summary>
        internal static string saving_info {
            get {
                return ResourceManager.GetString("saving_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Settings.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Steam username of signed on user.
        /// </summary>
        internal static string show_username {
            get {
                return ResourceManager.GetString("show_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string sign_in {
            get {
                return ResourceManager.GetString("sign_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        internal static string sign_out {
            get {
                return ResourceManager.GetString("sign_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed in as.
        /// </summary>
        internal static string signed_in_as {
            get {
                return ResourceManager.GetString("signed_in_as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Skip Current Game.
        /// </summary>
        internal static string skip_current_game {
            get {
                return ResourceManager.GetString("skip_current_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorting results based on your settings, please wait....
        /// </summary>
        internal static string sorting_results {
            get {
                return ResourceManager.GetString("sorting_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Statistics.
        /// </summary>
        internal static string statistics {
            get {
                return ResourceManager.GetString("statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam client status ignored.
        /// </summary>
        internal static string steam_ignored {
            get {
                return ResourceManager.GetString("steam_ignored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam is not running.
        /// </summary>
        internal static string steam_notrunning {
            get {
                return ResourceManager.GetString("steam_notrunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam is running.
        /// </summary>
        internal static string steam_running {
            get {
                return ResourceManager.GetString("steam_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Session.
        /// </summary>
        internal static string this_session {
            get {
                return ResourceManager.GetString("this_session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string total {
            get {
                return ResourceManager.GetString("total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Update.
        /// </summary>
        internal static string update {
            get {
                return ResourceManager.GetString("update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update games status.
        /// </summary>
        internal static string update_games_status {
            get {
                return ResourceManager.GetString("update_games_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data you&apos;ve entered isn&apos;t valid.  Please try again..
        /// </summary>
        internal static string validate_failed {
            get {
                return ResourceManager.GetString("validate_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating....
        /// </summary>
        internal static string validating {
            get {
                return ResourceManager.GetString("validating", resourceCulture);
            }
        }
    }
}
